### ISSUE TITLE
Add properties of testcase, not only from testsuite.

### ISSUE THREAD

**Issue by minuscorp** [lukejpreston/xunit-viewer#81]
Raise any issues using GitHub and provide sample data where possible.

To help debug any issues please provide the following info

* node 13.13.0 npm 6.14.4
* 6.2.0
* Chrome
* sample xml
```xml
<testsuite name='DELETED.BasicWebViewControllerTests' tests='8' failures='1'>

    <testcase classname='DELETED.BasicWebViewControllerTests' name='testCompletionIsCalledWhenResettingWebContentEarly' time='0.010'/>

    <testcase classname='DELETED.BasicWebViewControllerTests' name='testFullResetWebViewURL' time='0.011'/>

    <testcase classname='DELETED.BasicWebViewControllerTests' name='testIsBasedOnHostMatchingURLReturnsFalseWhenHostDoesNotMatch' time='0.008'/>

    <testcase classname='DELETED.BasicWebViewControllerTests' name='testIsBasedOnHostMatchingURLReturnsFalseWithNilDefaultURL' time='0.008'/>

    <testcase classname='DELETED.BasicWebViewControllerTests' name='testIsBasedOnHostMatchingURLReturnsTrueWhenHostMatches' time='0.008'/>

    <testcase classname='DELETED.BasicWebViewControllerTests' name='testLoadingFragmentURLSession' retries='1'>

      <failure message='Asynchronous wait failed: Exceeded timeout of 5 seconds, with unfulfilled expectations: &quot;testLoadingFragmentURLSession()&quot;.'>

        

        [DELETED]/BasicWebViewControllerTests.swift:103 

      </failure>

    </testcase>

    <testcase classname='DELETED.BasicWebViewControllerTests' name='testResetWebContentWithDefaultURL' time='1.481'/>

    <testcase classname='DELETED.BasicWebViewControllerTests' name='testResetWebContentWithNilDefaultURL' time='1.458'/>

  </testsuite>
```

I'd like to see the properties not only of the testsuite but of the test case itself, as can be seen in the example, the number of retries. This was being shown by the older package `junit-viewer` but not in this one. Could this be added?

**Comment by lukejpreston** [comment]
Good spot! I have just fixed this in `6.2.2`. Update to the latest version and re-open if it isn't doing what you expected.

Sorry for the delay. Due to COVID-19 the time I would normally have to work on this is now spent babysitting. Also, it looks like npm is down but it will be in that version when it is working again

![image](https://media.giphy.com/media/nEZkc87t9u68U/giphy.gif)

**Comment by minuscorp** [comment]
Still having the property, you cannot search for it in the header part
![image](https://user-images.githubusercontent.com/3819883/82229731-1bf66f00-992b-11ea-938c-5b76ba88d17b.png)

**Comment by lukejpreston** [comment]
that is part of this issue I think https://github.com/lukejpreston/xunit-viewer/issues/73
